### ISSUE TITLE
Support JSON-RPC Batches

### ISSUE THREAD

**Issue by Davenchy** [seprich/py-bson-rpc#10]
I think you can support batches now as specified in [BSON spec](https://bsonspec.org/spec.html).

- **Array**: The document for an array is a normal **BSON document** with **integer values for the keys**, starting with 0 and continuing sequentially.
 
For example, the array **['red', 'blue']** would be encoded as the document **{'0': 'red', '1': 'blue'}**. The keys must be in **ascending numerical order**.

**Comment by seprich** [comment]
Hi, thanks for showing interest in this lib. Currently the parsing of bson content is delegated to sub-libraries : either [bson](https://github.com/py-bson/bson) or [pymongo's bson](https://github.com/mongodb/mongo-python-driver) will do the actual parsing of each bson document. The current inability to handle array documents stems from the fact that neither of those libraries can serialize python array into bson encoded data. EDIT: And that is according to the specification.

The BSON spec starts with stating: 
> "BSON is a binary format in which zero or more ordered key/value pairs are stored as a single entity. We call this entity a document."

This means a document is always an object and cannot be of any other data type such as number or string or an array.

Document can **contain** an array under some key:
```
|	"\x04" e_name document	Array
```
and then the description of the encoding of this **sub-array** is the way as you pointed out. However at the top level array is not possible. (Top level lacks meta information about type because object is assumed -> it follows that parser cannot just "randomly" decide that this object is actually an array without the type information being available)
