### ISSUE TITLE
bsonrpc.exceptions.ServerError: Code: -32000 Message: Server error Details: 0

### ISSUE THREAD

**Issue by DK1231** [seprich/py-bson-rpc#6]
It works fine when I test on localhost，but got this error between two servers.

Traceback (most recent call last):
  File "client.py", line 71, in <module>
    main(sys.argv[1:])
  File "client.py", line 62, in main
    print(server.do_mission(2,path))
  File "/home/user/.local/lib/python3.6/site-packages/bsonrpc/util.py", line 35, in _curried
    name, *args, _____timeout=self._timeout, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/bsonrpc/rpc.py", line 96, in invoke_request
    raise result
bsonrpc.exceptions.ServerError: Code: -32000 Message: Server error Details: 0

**Comment by seprich** [comment]
There should be nothing specifically server instance dependent in this library. In theory different python versions and different dependency library versions in different machines could maybe cause some problems. JSON serialization is trivial and not under suspicion here but if you use BSON serialization then maybe your different servers have different bson libraries in use and maybe there exists some corner case where serializations are not compatible ?

From the above traceback alone it is not possible to deduct what the issue might be here. Can you show your code or alternatively make a tiny demonstrative server and client pair which you can post me. Better yet if you can attach a `docker-compose.yml` to spin up such containers which would trigger this issue (because i now strongly suspect this has something to do with incompatible bson libraries).
