### ISSUE TITLE
Jsonrpcprotocol

### ISSUE THREAD

**Issue by ghost** [seprich/py-bson-rpc#7]
Class Jsonrpcprotocol variable with_connectionin branch feature/asyncio What is with_connection?

**Comment by seprich** [comment]
- Questions should be asked on the Discussions area rather than making issues
- My original idea was indeed to make asyncio support part of this library, but after noodling around with the code, my conclusion is that asyncio model is so different that it makes more sense to implement a separate library for asyncio rather than attempting to unify everything (traditional threads, green-threads, and asyncio) into one library.
- Maybe that `with_connection` was supposed to contain a socket kind of object - not entirely sure at this point what the architecture was supposed to be like.
